server:
  port: 5207

spring:
  application:
    name: ribbon-client
  cloud:
    loadbalancer:
      retry:
        enabled: true #是否开启重试机制

    consul:
      host: 172.17.141.249
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 172.17.141.241



eureka-client:
  ribbon:
    OkToRetryOnAllOperations: true #对xxxx-service的所有请求在失败的时候都进行重试
    MaxAutoRetries: 1 #对xxxx-service当前实例的重试次数
    MaxAutoRetriesNextServer: 1 #切换xxxx-service实例的重试次数：



