server:
  port: 5301

spring:
  application:
    name: eureka-client # 服务名称

# Eureka注册中心配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:5201/eureka/

# Actuator监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*" #启用所有的监控端点，默认这些端点是禁用的

# Ribbon配置
ribbon:
  ReadTimeout: 3000    #响应超时时间
  ConnectTimeout: 3000 #连接超时时间
# MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
# MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
# OkToRetryOnAllOperations: false  #是否所有操作都重试






# 日志配置
logging:
  level:
    com:
      ky:
        note: debug
