server:
  port: 5301

spring:
  application:
    name: eureka-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://kamyam:5211/eureka/,http://sandy:5222/eureka/