server:
  port: 5402

security:
  oauth2:
    resource:
      #从认证授权中心上验证token
      tokenInfoUri: http://localhost:5401/oauth/check_token
      preferTokenInfo: true
    client:
      ###appid
      clientId: first-client
      ###appSecret
      clientSecret: noonewilleverguess
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ky-security?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
