server:
  port: 5222

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: sandy #指定了Eureka服务端的IP
  client:
    register-with-eureka: true #是否将服务注册到Eureka服务端，单机：false，集群true
    fetch-registry: true #是否从Eureka服务端获取服务信息，单机：false，集群true
    serviceUrl:
      defaultZone: http://kamyam:5211/eureka/ #集群可以配置多个
      