server:
  port: 5202
spring:
  application:
    name: consul-client
  cloud:
    consul:
      host: 172.17.141.249
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 172.17.141.241
